apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "secops.kavinduxo.com/v1alpha1",
          "kind": "Sentinel",
          "metadata": {
            "name": "sentinel-sample"
          },
          "spec": {
            "data": {
              "password": "hello123"
            },
            "secretName": "my-secret-name",
            "secretType": "BaseSecret"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2024-02-16T07:02:12Z"
    operators.operatorframework.io/builder: operator-sdk-v1.33.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: sentinel-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Sentinel is the Schema for the sentinels API
      displayName: Sentinel
      kind: Sentinel
      name: sentinels.secops.kavinduxo.com
      specDescriptors:
      - description: Data defines the key-value pair of data that should be secured
        displayName: Data
        path: data
      - description: Role defines is optional and for the RBAC secured type
        displayName: Role
        path: role
      - description: RoleBinding is optional and for the RBAC secured type
        displayName: Role Binding
        path: roleBinding
      - description: SecretName defines the name of the secret that should create
        displayName: Secret Name
        path: secretName
      - description: SecretType defines the Type of the secret severity
        displayName: Secret Type
        path: secretType
      - description: ServiceAccount is optional and for the RBAC secured type
        displayName: Service Account
        path: serviceAccount
      statusDescriptors:
      - description: Conditions store the status conditions of the Sentinel instances
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: Operator sentinel for secured secrets in the cluster
  displayName: sentinel
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - secops.kavinduxo.com
          resources:
          - sentinels
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - secops.kavinduxo.com
          resources:
          - sentinels/finalizers
          verbs:
          - update
        - apiGroups:
          - secops.kavinduxo.com
          resources:
          - sentinels/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: sentinel-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: sentinel-operator
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: sentinel-operator
          control-plane: controller-manager
        name: sentinel-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.14.1
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: kavinduxo/sentinel:0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: sentinel-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: sentinel-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sentinel
  - k8s
  - secretmanager
  links:
  - name: Sentinel Operator
    url: https://sentinel-operator.domain
  maintainers:
  - email: kavindu.xo@gmail.com
    name: kavindu
  maturity: alpha
  provider:
    name: kavinduxo
  version: 0.0.1
