---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - secops.kavinduxo.com
  resources:
  - rbachooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secops.kavinduxo.com
  resources:
  - rbachooks/finalizers
  verbs:
  - update
- apiGroups:
  - secops.kavinduxo.com
  resources:
  - rbachooks/status
  verbs:
  - get
  - patch
  - update
