---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.sentinal.com
  resources:
  - k8ssentinals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.sentinal.com
  resources:
  - k8ssentinals/finalizers
  verbs:
  - update
- apiGroups:
  - cache.sentinal.com
  resources:
  - k8ssentinals/status
  verbs:
  - get
  - patch
  - update
