apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cr-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cr-sa
  namespace: default
roleRef:
  kind: Role
  name: cr-role
  apiGroup: rbac.authorization.k8s.io
