apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rbachooks.check.crd.com
spec:
  group: check.crd.com
  # scope: cluster /** yet to decide Namespaced or cluster **/
  scope: Namespaced
  names:
    kind: RBACHook
    listKind: rbachooklist
    plural: rbachooks
    singular: rbachook
  subresources:
    status: {}    
  versions:
    - name: v1alpha1
      served: true
      storage: true